github actions code

diff --git a/.github/workflows/docker-pipeline.yml b/.github/workflows/docker-pipeline.yml
--- a/.github/workflows/docker-pipeline.yml
+++ b/.github/workflows/docker-pipeline.yml
@@ -29,6 +29,12 @@ jobs:
           bandit_output=$(bandit -r . -f json)
           echo "$bandit_output"
 
+          # Check if Bandit command failed
+          if [ $? -ne 0 ]; then
+            echo "Bandit command failed. Failing the workflow."
+            exit 1
+          fi
+
           # Check if there are any vulnerabilities with severity "CRITICAL"
           if echo "$bandit_output" | jq '.results[] | select(.issue_severity == "CRITICAL")' > /dev/null; then
             echo "Critical vulnerabilities found. Failing the workflow."
@@ -36,6 +42,7 @@ jobs:
           else
             echo "No critical vulnerabilities found. Proceeding with the workflow."
           fi
+
 
 
 
